  # frozen_string_literal: true

  ##### This file was generated by Gloss; any changes made here will be overwritten.
  ##### See src/ to make changes

module Gloss
  module Errors
    class BaseGlossError < StandardError
    end
    class TypeValidationError < BaseGlossError
    end
    class TypeError < BaseGlossError
    end
    class ParserError < BaseGlossError
    end
  end
end
