# frozen_string_literal: true

##### This file was generated by Gloss; any changes made here will be overwritten.
##### See src/ to make changes

module Gloss
  class Scope < Hash
    def [](k)
      fetch(k) { ||
        raise "Undefined expression for current scope: #{k}"
      }
    end
  end
end

