  
  ##### This file was generated by Gloss; any changes made here will be overwritten.
  ##### See / to make changes

require "pathname"
require "fileutils"
module Gloss
  class Writer
    def initialize(content, src_path, output = nil)
      @content = content
      @src_path = src_path
      @output = output
    end
    def run()
      write_to_output() { |otpt|
        sb = shebang
        (if sb
          otpt.puts(sb)
        end)
        otpt.puts(@content)
      }
    end
    private     def shebang()
      case @output
        when Pathname
          (if @output.executable?
            first_line = File.open(@src_path) { |f|
              f.readline
            }
            (if first_line.start_with?("#!")
              first_line
            else
              nil
            end)
          end)
        else
          nil
      end
    end
    private     def write_to_output(&blk)
      case @output
        when IO, StringIO
          yield(@output)
        else
          output = @output || Pathname.new(Utils.src_path_to_output_path(@src_path))
          unless           output.parent
.exist?
            FileUtils.mkdir_p(output.parent)
          end
          File.open(output, "wb") { |file|
            yield(file)
          }
          (if Config.prettify_output_executable_path
            system(Config.prettify_output_executable_path, @output.to_s)
          end)
      end
    end
  end
end
