  # frozen_string_literal: true

  ##### This file was generated by Gloss; any changes made here will be overwritten.
  ##### See src/ to make changes

require "pathname"
require "fileutils"
module Gloss
  class Writer
    def initialize(content, src_path, output_path = Pathname.new(Utils.src_path_to_output_path(src_path)))
      @content = content
      @src_path = src_path
      @output_path = output_path
    end
    def run()
      unless       @output_path.parent
.exist?
        FileUtils.mkdir_p(@output_path.parent)
      end
      File.open(@output_path, "wb") { |file|
        sb = shebang
        (if sb
          file.puts(sb)
        end)
        file.puts(@content)
      }
    end
    private     def shebang()
      (if @output_path.executable?
        first_line = File.open(@src_path) { |f|
          f.readline
        }
        (if first_line.start_with?("#!")
          first_line
        else
          nil
        end)
      else
        nil
      end)
    end
  end
end
