  
  ##### This file was generated by Gloss; any changes made here will be overwritten.
  ##### See / to make changes

require "rbs"
require "json"
require "steep"
require "fast_blank"
require "gloss/version"
require "gloss/cli"
require "gloss/watcher"
require "gloss/type_checker"
require "gloss/parser"
require "gloss/initializer"
require "gloss/config"
require "gloss/writer"
require "gloss/source"
require "gloss/scope"
require "gloss/visitor"
require "gloss/errors"
require "gloss/logger"
require "gloss/prog_loader"
require "gloss/utils"
require "gloss/runtime"
require "gls"
EMPTY_ARRAY = Array.new
.freeze
EMPTY_HASH = {}.freeze
