name: Self Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
      - uses: actions/checkout@v2
      - name: Install ruby
        run: apt-get update && apt-get install ruby=2.7 && which ruby
      - name: Build self
        run: gloss build
