name: Self Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  ImageOS: ubuntu18
jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: johansenja/gloss:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: gems-cache
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: install Bundler
        run: gem install bundler:2.2.3
      - name: install gems
        run: bundle install --jobs 4 --retry 3
      - name: build native extensions
        run: cd ext/gloss && make && cd -
      - name: Build self with current state
        run: exe/gloss build
