name: Self Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
      - uses: actions/checkout@v2
      - name: Install ruby
        run: apt-get update && apt-get install -y ruby && which ruby
      - uses: actions/cache@v2
        id: gems-cache
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: install gems
        run: bundle install --jobs 4 --retry 3
      - name: install shards
        working-directory: ext/gloss
        run: shards install
      - name: Build self with current state
        run: exe/gloss build
      - name: check installation from rubygems
        run: gem install gloss
