name: Self Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  ImageOS: ubuntu18
jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
      # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
      # change this to (see https://github.com/ruby/setup-ruby#versioning):
      # uses: ruby/setup-ruby@v1
        uses: ruby/setup-ruby@21351ecc0a7c196081abca5dc55b08f085efe09a
        with:
          ruby-version: 2.7
      - uses: actions/cache@v2
        id: gems-cache
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: install Bundler
        run: gem install bundler:2.2.3
      - name: install gems
        run: bundle install --jobs 4 --retry 3
      - name: build native extensions
        run: bundle exec rake build
      - name: Build self with current state
        run: exe/gloss build
      - name: check installation from rubygems
        run: gem install gloss
